"use client";
import {useState,type FormEvent} from "react";
import Link from "next/link";
import {ArrowUpRight} from "lucide-react";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {Checkbox} from "@/components/ui/checkbox";
import {Button} from "@/components/ui/button";
type Trip="srimangal"|"sylhet"|"haor"|"not-sure";
export function RequestForm({initialTrip}:{initialTrip?:string}){const [trip,setTrip]=useState<Trip>((["srimangal","sylhet","haor"].includes(initialTrip||"")?initialTrip:"not-sure") as Trip);const [consent,setConsent]=useState(false);const [state,setState]=useState<"idle"|"loading"|"error"|"done">("idle");const [error,setError]=useState("");const [reference,setReference]=useState("");
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!consent)return;setState("loading");setError("");const data=new FormData(e.currentTarget);const payload={name:data.get("name"),email:data.get("email"),phone:data.get("phone"),trip,travelers:Number(data.get("travelers")),date:data.get("date"),notes:data.get("notes"),parentsInterested:data.get("parentsInterested")==="yes",consent,website:data.get("website")};try{const response=await fetch("/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {reference?:string,error?:string};if(!response.ok)throw new Error(result.error||"Please try again.");setReference(result.reference||"");setState("done");}catch(err){setError(err instanceof Error?err.message:"Please try again.");setState("error");}}
if(state==="done")return <div className="form-panel success" role="status"><div className="success-icon">✓</div><div className="kicker">REQUEST RECEIVED</div><h2>Thank you. Let's make it a good trip.</h2><p>Your reference is <strong>{reference}</strong>. This is a planning request, not a confirmed booking. We'll use your contact details to follow up.</p><Link className="primary" href="/">Back to journeys <ArrowUpRight size={18}/></Link></div>;
return <form className="form-panel" onSubmit={submit}><div className="form-head"><h2>Trip request</h2><span>01 / 01</span></div><div className="form-grid"><label>Your name<Input name="name" placeholder="Name" autoComplete="name" required maxLength={90}/></label><label>Email address<Input name="email" type="email" placeholder="you@example.com" autoComplete="email" required maxLength={160}/></label><label>Phone or WhatsApp<Input name="phone" type="tel" placeholder="Include country code if abroad" autoComplete="tel" required maxLength={35}/></label><label>Number of travelers<NativeSelect name="travelers" defaultValue="2">{[1,2,3,4].map(n=><NativeSelectOption key={n} value={String(n)}>{n} traveler{n>1?"s":""}</NativeSelectOption>)}</NativeSelect></label><label className="full">Which journey interests you?<NativeSelect value={trip} onChange={e=>setTrip(e.target.value as Trip)}><NativeSelectOption value="srimangal">Srimangal · calm hotel stay</NativeSelectOption><NativeSelectOption value="sylhet">Sylhet · gentle escape</NativeSelectOption><NativeSelectOption value="haor">Tanguar Haor · boat candidate</NativeSelectOption><NativeSelectOption value="not-sure">Not sure yet</NativeSelectOption></NativeSelect></label><label className="full">When might they like to travel?<Input name="date" placeholder="A month or a few possible dates" maxLength={100}/></label><label className="full">Have you spoken with your parents?<NativeSelect name="parentsInterested" defaultValue="not-yet"><NativeSelectOption value="yes">Yes, they're interested</NativeSelectOption><NativeSelectOption value="not-yet">Not yet, I'm exploring the idea</NativeSelectOption></NativeSelect></label><label className="full">What would make the trip comfortable?<Textarea name="notes" placeholder="For example: fewer stairs or frequent rest stops. Please don't include medical records." maxLength={1000} rows={4}/></label></div><div className="consent"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">I agree to be contacted about this request. I understand no reservation or payment is made now.</label></div><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/>{state==="error"&&<p className="form-error" role="alert">{error}</p>}<Button className="primary submit" type="submit" disabled={!consent||state==="loading"}>{state==="loading"?"Sending request...":"Send trip request"}<ArrowUpRight size={18}/></Button><p className="fine">We use your details to respond to this request. Please share travel needs without sensitive medical information.</p></form>}
