import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Heart, MapPin, ShieldCheck } from "lucide-react";

const trips = [
  { title: "Slow days in Srimangal", place: "SRIMANGAL · HOTEL BASED", description: "Tea gardens, good food and time to rest. A private car and a plan that follows your parents' pace.", trip: "srimangal", tag: "Suggested first trip" },
  { title: "A gentle Sylhet escape", place: "SYLHET · HOTEL BASED", description: "An easy way to see Sylhet, with considered stops and room to change the plan.", trip: "sylhet", tag: "Plan together" },
  { title: "A night on the haor", place: "TANGUAR HAOR · BOAT CANDIDATE", description: "A Nautilus trip for parents comfortable with boarding and limited access to shore. Suitability comes first.", trip: "haor", tag: "Subject to review" },
];

export default function Home() {return <main><header className="site-header"><Link className="brand" href="/"><b>b<span>.</span></b> bela <small>journeys</small></Link><nav><a href="#how">How it works</a><a href="#journeys">Journeys</a><Link className="nav-cta" href="/request">Plan a trip <ArrowUpRight size={17}/></Link></nav></header>
<section className="hero"><div className="hero-copy"><div className="kicker">A NEW WAY TO GIVE THEM A BREAK</div><h1>They made room for your world.<br/><em>Make room for theirs.</em></h1><p>Thoughtful holidays for your parents, planned with them and arranged by you. We handle the details so they can enjoy the trip on their own terms.</p><div className="actions"><Link className="primary" href="/request">Start planning <ArrowUpRight size={18}/></Link><a href="#how">See how it works ↓</a></div><div className="hero-foot">Made for families in Bangladesh <span>·</span> Built around the people going</div></div><div className="hero-image"><Image src="/parents-tea-garden.jpg" alt="An older couple sitting together overlooking tea gardens" fill priority sizes="(max-width:900px) 100vw, 49vw"/><span>More time together. More room to breathe.</span></div></section>
<section className="intro" id="how"><div className="kicker">THE IDEA</div><div><h2>A gift they actually get to enjoy.</h2><p>“Amma, Abbu, I've arranged everything.” Making that feel easy takes care: the right pace, clear details, comfortable handoffs and a real person to call when plans change.</p></div></section>
<section className="steps"><article><span>01</span><Heart size={27}/><h3>Tell us about them</h3><p>Where they want to go, what they enjoy and what makes travel comfortable. We speak with your parents too.</p></article><article><span>02</span><MapPin size={27}/><h3>Shape the journey</h3><p>We propose a relaxed itinerary, clear inclusions and a quote to review before anything is booked.</p></article><article><span>03</span><ShieldCheck size={27}/><h3>Know they're supported</h3><p>Confirmed arrangements, a reachable coordinator and the updates your parents agree to share.</p></article></section>
<section className="journeys" id="journeys"><div className="section-top"><div><div className="kicker">WHERE TO BEGIN</div><h2>Journeys with breathing room.</h2></div><p>Every trip is a starting point. We confirm accessibility, availability and the full quote before you decide.</p></div><div className="cards">{trips.map((t,i)=><article className="card" key={t.trip}><div className={`card-art art-${i}`}><span>0{i+1}</span><strong>{i===2?"≈":i===1?"✳":"◌"}</strong><small>{t.tag}</small></div><div className="card-body"><small>{t.place}</small><h3>{t.title}</h3><p>{t.description}</p><Link href={`/request?trip=${t.trip}`}>Explore this trip <ArrowUpRight size={17}/></Link></div></article>)}</div><p className="fine">No instant bookings or fixed package prices yet. Requests are reviewed with the travelers before a reservation is made.</p></section>
<section className="promise"><div className="kicker">A GOOD TRIP FEELS LIKE THEIRS</div><h2>Care, without taking over.</h2><p>Some parents want a full day out. Others want to sit by a window with tea. We ask them, respect the answer and design the trip around it. You can stay informed without making them feel watched.</p><Link className="light-button" href="/request">Tell us what they would love <ArrowUpRight size={18}/></Link></section><footer><div className="brand">b<span>.</span> bela <small>journeys</small></div><p>Thoughtful travel for parents in Bangladesh.</p><Link href="/request">Plan a trip</Link><small>Early pilot concept · All trips subject to availability, suitability and a confirmed operator agreement.</small></footer></main>}
